version: "3.8"

services:
  traefik:
    command:
      - --accessLog=true
      - --api.insecure=false
      - --api.dashboard=true
      - --api.debug=false
      - --certificatesresolvers.http.acme.httpchallenge=true
      - --certificatesresolvers.http.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.http.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.http.acme.storage=/acme/acme.json
      #- --certificatesResolvers.dns.acme.dnsChallenge.delayBeforeCheck=60
      #- --certificatesResolvers.dns.acme.dnsChallenge.provider=${DNS_PROVIDER}
      #- --certificatesResolvers.dns.acme.email=${ACME_EMAIL}
      #- --certificatesResolvers.dns.acme.storage=/acme/acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --log.level=WARNING
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      - --providers.file.directory=/config
      - --providers.file.watch=true
    environment:
      - NAMECHEAP_API_USER
      - NAMECHEAP_API_KEY
      - CF_API_EMAIL
      - CF_API_KEY
    labels:
      traefik.http.middlewares.traefik-auth.basicauth.users: ${TRAEFIK_BASICAUTH_USERS}
      traefik.http.routers.traefik.middlewares: traefik-auth
      traefik.http.routers.traefik.tls.certresolver: http
    volumes:
      - ./config/services/traefik/config/live/dynamic.yml:/config/live.yml
      - ./config/services/traefik/config/local/dynamic.yml:/config/local.yml
      - ./acme:/acme
      - ./config/services/traefik/certs:/certs
