---
- name: Ensure system is ready and up-to-date
  hosts: all
  become: yes
  tasks:

    - name: Wait for apt list lock (Known to cause issues sometimes)
      raw: while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do echo 'Waiting for apt list lock.' && sleep 10; done
      changed_when: False

    - name: Ensure packages are updated
      apt:
        update_cache: yes
        upgrade: dist
        autoclean: yes
        autoremove: yes

    - name: Install a list of packages
      apt:
        pkg:
          - unzip

- name: Ensure firewall is set up
  hosts: all
  become: yes
  vars:
    firewall_state: started
    firewall_enabled_at_boot: true
    firewall_allowed_tcp_ports:
      - 22
      - 80
      - 443
      - 4443
    firewall_allowed_udp_ports:
      - 10000
    firewall_disable_ufw: true
    firewall_enable_ipv6: false
  roles:
    - geerlingguy.firewall

- name: Ensure Docker is installed
  hosts: all
  become: yes
  vars:
    docker_package_state: present
    docker_users:
      - "{{ primary_ssh_user }}"
    docker_install_compose: true
    docker_service_state: restarted
  roles:
    - geerlingguy.docker

- name: Ensure Docker Python library is installed
  hosts: all
  become: yes
  vars:
    pip_executable: pip3
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
        state: present
        version: 4.4.0
  roles:
    - geerlingguy.pip
