#!/usr/bin/env bash

if [[ "${DEPLOYMENT_ENVIRONMENT}" == "dev" ]]
then
   DC_PREFIX=""
elif [[ "${DEPLOYMENT_ENVIRONMENT}" == "live" ]]
then
    DC_PREFIX=" -f ${PROJECT_ROOT}/docker-compose.yml -f ${PROJECT_ROOT}/config/docker/compose/live.yml"
elif [[ "${DEPLOYMENT_ENVIRONMENT}" == "local" ]]
then
    DC_PREFIX=" -f ${PROJECT_ROOT}/docker-compose.yml -f ${PROJECT_ROOT}/config/docker/compose/local.yml"
else
   >&2 echo "Invalid DEPLOYMENT_ENVIRONMENT=${DEPLOYMENT_ENVIRONMENT}"
   exit 1
fi
unwrapped_command="/usr/local/bin/docker-compose${DC_PREFIX} $@"
>&2 echo "********************************************************************************"
>&2 echo "NOTE: Command is unwrapped to the following (to apply to correct environment):"
>&2 echo ""
>&2 echo "$ ${unwrapped_command}"
>&2 echo "********************************************************************************"
eval "${unwrapped_command}"
